
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Dec 17 20:51:53 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEMI_COLON = 3;
  public static final int error = 1;
  public static final int NUMBER = 5;
  public static final int IDENT = 4;
  public static final int EOF = 0;
  public static final int PROGRAM = 2;
}

