
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Dec 19 01:19:54 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RIGHT_BRACKET = 32;
  public static final int INCREMENT = 24;
  public static final int ASSIGNMENT = 38;
  public static final int EQUALS = 39;
  public static final int FOR_EACH = 10;
  public static final int CONTINUE = 6;
  public static final int GREATER_OR_EQUAL_THAN = 43;
  public static final int DECREMENT = 25;
  public static final int GREATER_THAN = 41;
  public static final int STATIC = 17;
  public static final int LEFT_PARENTHESES = 29;
  public static final int AND = 26;
  public static final int OR = 27;
  public static final int LEFT_BRACE = 33;
  public static final int CLASS = 11;
  public static final int SUBTRACTION = 20;
  public static final int IF = 14;
  public static final int DOT = 35;
  public static final int EOF = 0;
  public static final int LESS_OR_EQUAL_THAN = 44;
  public static final int LAMBDA = 28;
  public static final int NEW = 13;
  public static final int error = 1;
  public static final int CONST_BOOLEAN = 18;
  public static final int PROGRAM = 2;
  public static final int SEMI_COLON = 37;
  public static final int MODULO = 23;
  public static final int RIGHT_BRACE = 34;
  public static final int NUMBER = 4;
  public static final int BREAK = 5;
  public static final int COLON = 36;
  public static final int RIGHT_PARENTHESES = 30;
  public static final int ELSE = 15;
  public static final int READ = 7;
  public static final int WHILE = 9;
  public static final int NOT_EQUALS = 40;
  public static final int ADDITION = 19;
  public static final int THEN = 16;
  public static final int EXTENDS = 12;
  public static final int DIVISION = 22;
  public static final int LESS_THAN = 42;
  public static final int LEFT_BRACKET = 31;
  public static final int MULTIPLICATION = 21;
  public static final int PRINT = 8;
  public static final int IDENTIFIER = 3;
}

