
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Dec 22 00:05:25 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RIGHT_BRACKET = 34;
  public static final int INCREMENT = 26;
  public static final int CONST = 9;
  public static final int ASSIGNMENT = 40;
  public static final int EQUALS = 41;
  public static final int FOR_EACH = 17;
  public static final int CONTINUE = 16;
  public static final int GREATER_OR_EQUAL_THAN = 45;
  public static final int DECREMENT = 27;
  public static final int GREATER_THAN = 43;
  public static final int STATIC = 19;
  public static final int LEFT_PARENTHESES = 31;
  public static final int AND = 28;
  public static final int OR = 29;
  public static final int COMMA = 38;
  public static final int LEFT_BRACE = 35;
  public static final int CLASS = 7;
  public static final int SUBTRACTION = 22;
  public static final int IF = 10;
  public static final int DOT = 37;
  public static final int EOF = 0;
  public static final int LESS_OR_EQUAL_THAN = 46;
  public static final int LAMBDA = 30;
  public static final int NEW = 12;
  public static final int error = 1;
  public static final int CONST_BOOLEAN = 20;
  public static final int PROGRAM = 5;
  public static final int CONST_NUMBER = 3;
  public static final int SEMI_COLON = 39;
  public static final int MODULO = 25;
  public static final int RIGHT_BRACE = 36;
  public static final int BREAK = 6;
  public static final int CONST_CHARACTER = 4;
  public static final int RIGHT_PARENTHESES = 32;
  public static final int ELSE = 8;
  public static final int READ = 14;
  public static final int WHILE = 11;
  public static final int NOT_EQUALS = 42;
  public static final int ADDITION = 21;
  public static final int THEN = 18;
  public static final int EXTENDS = 15;
  public static final int DIVISION = 24;
  public static final int LESS_THAN = 44;
  public static final int LEFT_BRACKET = 33;
  public static final int MULTIPLICATION = 23;
  public static final int PRINT = 13;
  public static final int IDENTIFIER = 2;
}

